#ifndef CONFIG_USER_H
#define CONFIG_USER_H 1

#include "config.h"

#undef MOUSEKEY_TIME_TO_MAX
#undef MOUSEKEY_MAX_SPEED

#define MOUSEKEY_TIME_TO_MAX 1
#define MOUSEKEY_MAX_SPEED 2

#define ONESHOT_TAP_TOGGLE 2
#define ONESHOT_TIMEOUT 3000

#endif
