#!/bin/sh
set -e

cmd_wm () {
    WIN="$(xdotool getactivewindow)"
    wmctrl -i -r ${WIN} -b remove,maximized_vert,maximized_horz
    xdotool windowsize ${WIN} 100% 100%
    wmctrl -i -r ${WIN} -b add,maximized_vert,maximized_horz
}

cmd_help () {
    cat <<EOF
Use the source, Luke!
EOF
}

while read l; do
    case "$l" in
        "CMD:"*)
            ;;
        *)
            continue
            ;;
    esac

    cmd="$(echo $l | cut -d: -f2-)"

    if type -t cmd_${cmd} >/dev/null 2>&1; then
        cmd_${cmd}
    fi
done


